@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Feb 02 20:23:27 +0700 2024
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim mmu_TB_behav -key {Behavioral:sim_1:Functional:mmu_TB} -tclbatch mmu_TB.tcl -view E:/MMU/MMU-master/MMU-master/Memory_Management_Unit/Translation_Buffer_tb_behav.wcfg -view E:/MMU/MMU-master/MMU-master/Memory_Management_Unit/mmu_TB_behav.wcfg -log simulate.log"
call xsim  mmu_TB_behav -key {Behavioral:sim_1:Functional:mmu_TB} -tclbatch mmu_TB.tcl -view E:/MMU/MMU-master/MMU-master/Memory_Management_Unit/Translation_Buffer_tb_behav.wcfg -view E:/MMU/MMU-master/MMU-master/Memory_Management_Unit/mmu_TB_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
